/* eslint @typescript-eslint/no-unused-vars: off */
/**
 * Sample API
 * Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
 *
 * The version of the OpenAPI document: 0.1.9
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    AnyPetDto,
    CatAllOfDto,
    CatDto,
    DogAllOfDto,
    DogDto,
    PetDto,
} from "../model";

import {
    DefaultApiInterface,
} from "../api";

function reject(operation: string) {
    return () => Promise.reject(new Error("Unexpected function call " + operation));
}

export function mockDefaultApi(operations: {
    petsPatch?: () => Promise<void>;
}): DefaultApiInterface {
    return {
        petsPatch: operations.petsPatch || reject("petsPatch"),
    };
}
