/* eslint @typescript-eslint/no-unused-vars: off */
/**
 * GeoJSON
 * GeoJSON
 *
 * The version of the OpenAPI document: 0.1.9
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    GeometryCollectionDto,
    GeometryDto,
    LineStringDto,
    PointDto,
    PolygonDto,
} from "./model";

import { BaseAPI, RequestCallOptions, SecurityScheme } from "./base";

export interface ApplicationApis {
    defaultApi: DefaultApiInterface;
}

/**
 * DefaultApi - object-oriented interface
 */
export interface DefaultApiInterface {
    /**
     *
     * @throws {HttpError}
     */
    getGeometry(params?: RequestCallOptions): Promise<GeometryDto>;
    /**
     *
     * @throws {HttpError}
     */
    getLocation(params?: RequestCallOptions): Promise<GeometryCollectionDto>;
    /**
     *
     * @throws {HttpError}
     */
    getPolygon(params?: RequestCallOptions): Promise<PolygonDto>;
}

/**
 * DefaultApi - object-oriented interface
 */
export class DefaultApi extends BaseAPI implements DefaultApiInterface {
    /**
     *
     * @throws {HttpError}
     */
    public async getGeometry(params: RequestCallOptions = {}): Promise<GeometryDto> {
        return await this.fetch(
            this.basePath + "/geometry", params
        );
    }
    /**
     *
     * @throws {HttpError}
     */
    public async getLocation(params: RequestCallOptions = {}): Promise<GeometryCollectionDto> {
        return await this.fetch(
            this.basePath + "/collection", params
        );
    }
    /**
     *
     * @throws {HttpError}
     */
    public async getPolygon(params: RequestCallOptions = {}): Promise<PolygonDto> {
        return await this.fetch(
            this.basePath + "/polygon", params
        );
    }
}

type ServerNames =
    | "Server";

export const servers: Record<ServerNames, ApplicationApis> = {
    "Server": {
        defaultApi: new DefaultApi("/v1"),
    },
};

