/**
 * OpenAPI Petstore
 * This is a sample server Petstore server. For this sample, you can use the api key \"special-key\" to test the authorization filters
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface CategoryDto {
    id?: number;
    name?: string;
}

export interface OrderDto {
    id?: number;
    petId?: number;
    quantity?: number;
    shipDate?: Date;
    /**
     * Order Status
     */
    status?: OrderDtoStatusEnum;
    complete?: boolean;
}
/**
 * Order Status
 */
export type OrderDtoStatusEnum =
    | "placed"
    | "approved"
    | "delivered";

export const OrderDtoStatusEnumValues: OrderDtoStatusEnum[] = [
    "placed",
    "approved",
    "delivered",
];

export interface PetDto {
    id?: number;
    category?: CategoryDto;
    name: string;
    photoUrls: Array<string>;
    tags?: Array<TagDto>;
    /**
     * pet status in the store
     */
    status?: PetDtoStatusEnum;
}
/**
 * pet status in the store
 */
export type PetDtoStatusEnum =
    | "available"
    | "pending"
    | "sold";

export const PetDtoStatusEnumValues: PetDtoStatusEnum[] = [
    "available",
    "pending",
    "sold",
];

export interface TagDto {
    id?: number;
    name?: string;
}

export interface UserDto {
    id?: number;
    username?: string;
    firstName?: string;
    lastName?: string;
    email?: string;
    password?: string;
    phone?: string;
    /**
     * User Status
     */
    userStatus?: number;
}
