/**
 * OpenAPI Petstore
 * This is a sample server Petstore server. For this sample, you can use the api key \"special-key\" to test the authorization filters
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface CategoryDto {
    id?: number;
    name?: string;
}

export interface InlineObject1Dto {
    /**
     * Additional data to pass to server
     */
    additionalMetadata?: string;
    /**
     * file to upload
     */
    file?: Blob;
}

export interface InlineObjectDto {
    /**
     * Updated name of the pet
     */
    name?: string;
    /**
     * Updated status of the pet
     */
    status?: string;
}

export interface OrderDto {
    id?: number;
    petId?: number;
    quantity?: number;
    shipDate?: Date;
    /**
     * Order Status
     */
    status?: OrderDtoStatusDtoEnum;
    complete?: boolean;
}
/**
 * Order Status
 */
export type OrderDtoStatusDtoEnum =
    | "placed"
    | "approved"
    | "delivered";

export const OrderDtoStatusDtoEnumValues: OrderDtoStatusDtoEnum[] = [
    "placed",
    "approved",
    "delivered",
];

export interface PetDto {
    id?: number;
    category?: CategoryDto;
    name: string;
    photoUrls: Array<string>;
    tags?: Array<TagDto>;
    /**
     * pet status in the store
     */
    status?: PetDtoStatusDtoEnum;
}
/**
 * pet status in the store
 */
export type PetDtoStatusDtoEnum =
    | "available"
    | "pending"
    | "sold";

export const PetDtoStatusDtoEnumValues: PetDtoStatusDtoEnum[] = [
    "available",
    "pending",
    "sold",
];

export interface TagDto {
    id?: number;
    name?: string;
}

export interface UserDto {
    id?: number;
    username?: string;
    firstName?: string;
    lastName?: string;
    email?: string;
    password?: string;
    phone?: string;
    /**
     * User Status
     */
    userStatus?: number;
}
