/* eslint @typescript-eslint/no-unused-vars: off */
/**
 * Conversations
 * Conversations for real time and offline peer-to-peer web chat
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    AddMessageToConversationDeltaDto,
    ChangeTrackedDto,
    CommandToServerDto,
    ConversationInfoDto,
    ConversationMessageDto,
    ConversationMessageSnapshotDto,
    ConversationSnapshotDto,
    CreateConversationDeltaDto,
    DeltaDto,
    EventFromServerDto,
    MessageFromServerDto,
    MessageToServerDto,
    RequestToServerDto,
    SnapshotSetDto,
    SubscribeRequestDto,
    UpdateConversationDeltaDto,
} from "./model";

import { BaseAPI, RequestCallOptions, SecurityScheme } from "./base";

export interface ApplicationApis {
    defaultApi: DefaultApiInterface;
}

/**
 * DefaultApi - object-oriented interface
 */
export interface DefaultApiInterface {
    /**
     *
     * @param {*} [params] Request parameters, including pathParams, queryParams (including bodyParams) and http options.
     * @throws {HttpError}
     */
    apiCommandsPost(params: {
        commandToServerDto: CommandToServerDto;
    } & RequestCallOptions): Promise<void>;
    /**
     *
     * @throws {HttpError}
     */
    apiConversationsGet(params?: RequestCallOptions): Promise<Array<ConversationSnapshotDto>>;
}

/**
 * DefaultApi - object-oriented interface
 */
export class DefaultApi extends BaseAPI implements DefaultApiInterface {
    /**
     *
     * @param {*} [params] Request parameters, including pathParams, queryParams (including bodyParams) and http options.
     * @throws {HttpError}
     */
    public async apiCommandsPost(params: {
        commandToServerDto: CommandToServerDto;
    } & RequestCallOptions): Promise<void> {
        return await this.fetch(
            this.basePath + "/api/commands",
            {
                ...params,
                method: "POST",
                body: JSON.stringify(params.commandToServerDto),
                headers: {
                    ...this.removeEmpty(params.headers),
                    "Content-Type": "application/json",
                },
            }
        );
    }
    /**
     *
     * @throws {HttpError}
     */
    public async apiConversationsGet(params: RequestCallOptions = {}): Promise<Array<ConversationSnapshotDto>> {
        return await this.fetch(
            this.basePath + "/api/conversations", params
        );
    }
}

type ServerNames =
    | "default";

export const servers: Record<ServerNames, ApplicationApis> = {
    default: {
        defaultApi: new DefaultApi(""),
    },
};

