/**
 * User database
 * User database
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface UserDto {
    readonly id?: number;
    username: string;
    emailAddress?: string;
    updatedAt: Date;
    password: string;
    permissions: Array<UserPermissionDto>;
}

export interface UserPermissionDto {
    permission: UserPermissionDtoPermissionEnum;
    readonly updatedAt?: Date;
}

export const UserPermissionDtoPermissionEnumValues = [
    "create users",
    "list users",
    "create groups",
    "list groups",
] as const;

export type UserPermissionDtoPermissionEnum = typeof UserPermissionDtoPermissionEnumValues[number];
