/**
 * User database
 * User database
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface UserDto {
    id: number;
    username: string;
    emailAddress?: string;
    updatedAt: Date;
    password: string;
    permissions: Array<UserPermissionDto>;
}

export type UserDtoRequest = Omit<UserDto, "id"|"updatedAt"|"permissions">
    & { permissions: Array<UserPermissionDtoRequest> };

export interface UserPermissionDto {
    permission: UserPermissionDtoPermissionEnum;
    updatedAt: Date;
}

export type UserPermissionDtoRequest = Omit<UserPermissionDto, "updatedAt">;

export const UserPermissionDtoPermissionEnumValues = [
    "create users",
    "list users",
    "create groups",
    "list groups",
] as const;

export type UserPermissionDtoPermissionEnum = typeof UserPermissionDtoPermissionEnumValues[number];
