/* eslint @typescript-eslint/no-unused-vars: off */
/**
 * Open ID Connect
 * Open ID Connect Discovery
 *
 * The version of the OpenAPI document: 1.0.0-draft
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    DiscoveryDocumentDto,
    JwksDocumentDto,
    JwksKeyDto,
    JwtHeaderDto,
    JwtPayloadDto,
    TokenResponseDto,
} from "./model";

import { BaseAPI, SecurityScheme } from "./base";

export interface ApplicationApis {
    defaultApi: DefaultApiInterface;
}

/**
 * DefaultApi - object-oriented interface
 */
export interface DefaultApiInterface {
    /**
     *
     * @throws {HttpError}
     */
    wellKnownKeysGet(): Promise<JwksDocumentDto>;
    /**
     *
     * @throws {HttpError}
     */
    wellKnownOpenidConfigurationGet(): Promise<DiscoveryDocumentDto>;
}

/**
 * DefaultApi - object-oriented interface
 */
export class DefaultApi extends BaseAPI implements DefaultApiInterface {
    /**
     *
     * @throws {HttpError}
     */
    public async wellKnownKeysGet(): Promise<JwksDocumentDto> {
        return await this.fetch(
            this.basePath + "/.well-known/keys"
        );
    }
    /**
     *
     * @throws {HttpError}
     */
    public async wellKnownOpenidConfigurationGet(): Promise<DiscoveryDocumentDto> {
        return await this.fetch(
            this.basePath + "/.well-known/openid-configuration"
        );
    }
}

type ServerNames =
    | "default";

export const servers: Record<ServerNames, ApplicationApis> = {
    default: {
        defaultApi: new DefaultApi(""),
    },
};

