/* eslint @typescript-eslint/no-unused-vars: off */
/**
 * ReqRes API
 * Fake data CRUD API
 *
 * The version of the OpenAPI document: 1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    LoginPost200ResponseDto,
    LoginPost400ResponseDto,
    LoginPostRequestDto,
    RegisterPost200ResponseDto,
    UnknownResourceDto,
    UserDto,
    UsersGet200ResponseDto,
    UsersIdDelete200Response1Dto,
    UsersIdDelete200ResponseDto,
} from "../model";

import {
    ApplicationApis,
    DefaultApiInterface,
} from "../api";

function reject(operation: string) {
    return () => Promise.reject(new Error("Unexpected function call " + operation));
}

export function mockApplicationApis({
    defaultApi = mockDefaultApi(),
}: Partial<ApplicationApis> = {}): ApplicationApis {
    return { defaultApi };
}

export function mockDefaultApi(
    operations: Partial<DefaultApiInterface> = {}
): DefaultApiInterface {
    return {
        loginPost: operations.loginPost || reject("DefaultApi.loginPost"),
        logoutPost: operations.logoutPost || reject("DefaultApi.logoutPost"),
        registerPost: operations.registerPost || reject("DefaultApi.registerPost"),
        usersGet: operations.usersGet || reject("DefaultApi.usersGet"),
        usersIdDelete: operations.usersIdDelete || reject("DefaultApi.usersIdDelete"),
        usersIdGet: operations.usersIdGet || reject("DefaultApi.usersIdGet"),
        usersIdPatch: operations.usersIdPatch || reject("DefaultApi.usersIdPatch"),
        usersIdPut: operations.usersIdPut || reject("DefaultApi.usersIdPut"),
    };
}
