/* eslint @typescript-eslint/no-unused-vars: off */
/**
 * GeoJSON
 * GeoJSON
 *
 * The version of the OpenAPI document: 0.1.9
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    GeometryCollectionDto,
    GeometryDto,
    LineStringDto,
    PointDto,
    PolygonDto,
} from "../model";

import {
    ApplicationApis,
    DefaultApiInterface,
} from "../api";

function reject(operation: string) {
    return () => Promise.reject(new Error("Unexpected function call " + operation));
}

export function mockApplicationApis({
    defaultApi = mockDefaultApi(),
}: Partial<ApplicationApis> = {}): ApplicationApis {
    return { defaultApi };
}

export function mockDefaultApi(
    operations: Partial<DefaultApiInterface> = {}
): DefaultApiInterface {
    return {
        getGeometry: operations.getGeometry || reject("DefaultApi.getGeometry"),
        getLocation: operations.getLocation || reject("DefaultApi.getLocation"),
        getPolygon: operations.getPolygon || reject("DefaultApi.getPolygon"),
    };
}
