/**
 * FakeRESTApi.Web V1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface ActivityDto {
    id?: number;
    title?: string | null;
    dueDate?: Date;
    completed?: boolean;
}

export interface AuthorDto {
    id?: number;
    idBook?: number;
    firstName?: string | null;
    lastName?: string | null;
}

export interface BookDto {
    id?: number;
    title?: string | null;
    description?: string | null;
    pageCount?: number;
    excerpt?: string | null;
    publishDate?: Date;
}

export interface CoverPhotoDto {
    id?: number;
    idBook?: number;
    url?: string | null;
}

export interface UserDto {
    id?: number;
    userName?: string | null;
    password?: string | null;
}
