// tslint:disable
/**
 * Infection Tracker
 * Infection Tracker - A case management system for tracking the spread of diseases
 *
 * The version of the OpenAPI document: 1.0.0-draft
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import {
        CaseWorkerDto,
        ExposureDto,
        InfectionDto,
        InfectionInformationDto,
        UserRoleDto,
} from "../model";

import {
    CaseWorkersApiInterface,
    CasesApiInterface,
    ExposuresApiInterface,
} from "../api";




export function mockCaseWorkersApi(operations: {
        listCaseWorkers?: () => Promise<CaseWorkerDto>
        registerCaseWorker?: () => Promise<void>
}): CaseWorkersApiInterface {
    const reject = (operation: string) => () => Promise.reject(new Error("Unexpected function call " + operation));
    return {
        listCaseWorkers: (operations.listCaseWorkers || reject("listCaseWorkers")),
        registerCaseWorker: (operations.registerCaseWorker || reject("registerCaseWorker")),
    };
}


export function mockCasesApi(operations: {
        getCaseDetails?: () => Promise<InfectionDto>
        listCases?: () => Promise<InfectionDto>
        newCase?: () => Promise<void>
        registerExposure?: () => Promise<void>
}): CasesApiInterface {
    const reject = (operation: string) => () => Promise.reject(new Error("Unexpected function call " + operation));
    return {
        getCaseDetails: (operations.getCaseDetails || reject("getCaseDetails")),
        listCases: (operations.listCases || reject("listCases")),
        newCase: (operations.newCase || reject("newCase")),
        registerExposure: (operations.registerExposure || reject("registerExposure")),
    };
}


export function mockExposuresApi(operations: {
        listExposures?: () => Promise<ExposureDto>
        updateExposure?: () => Promise<void>
}): ExposuresApiInterface {
    const reject = (operation: string) => () => Promise.reject(new Error("Unexpected function call " + operation));
    return {
        listExposures: (operations.listExposures || reject("listExposures")),
        updateExposure: (operations.updateExposure || reject("updateExposure")),
    };
}
