/**
 * WebSockets
 * An example of sending requests and commands
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: johannes@brodwall.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface ChangeTrackedDto {
    createdAt: Date;
    createdBy: string;
    updatedAt?: Date;
    updatedBy?: string;
}

export interface CreatePersonCommandDto {
    command: "createPerson";
    id: string;
    person: PersonDto;
}

export interface PersonDto extends RecipientDto {
    readonly id?: string;
    type?: string;
    name?: PersonNameDto;
    phone?: string;
    birthDate?: Date;
}

export interface PersonNameDto {
    givenName?: string;
    familyName?: string;
}

export interface PersonSnapshotAllOfDto {
    extra?: string;
}

export type PersonSnapshotDto = ChangeTrackedDto & PersonDto & PersonSnapshotAllOfDto;

export interface RecipientDto {
    email?: string;
}

export interface StringSnapshotDto extends ChangeTrackedDto {
    name?: string;
    type?: string;
}

export interface SubscribeDto {
    request: "Subscribe";
}

export interface UnsubscribeDto {
    request: "Unsubscribe";
}

export interface UpdatePersonCommandDto {
    command: "updatePerson";
    id: string;
    person: PersonDto;
}

export type WebSocketCommandDto =
    { command: "createPerson" } & CreatePersonCommandDto |
    { command: "updatePerson" } & UpdatePersonCommandDto;

export const WebSocketCommandDtoDescriminators = [
    "createPerson",
    "updatePerson",
] as const;

export type WebSocketCommandDtoDescriminator = typeof WebSocketCommandDtoDescriminators[number];

export type WebSocketMessageDto = WebSocketCommandDto | WebSocketRequestDto;

export type WebSocketRequestDto =
    { request: "Subscribe" } & SubscribeDto;

export const WebSocketRequestDtoDescriminators = [
    "Subscribe",
] as const;

export type WebSocketRequestDtoDescriminator = typeof WebSocketRequestDtoDescriminators[number];
