/**
 * WebSockets
 * An example of sending requests and commands
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: johannes@brodwall.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface CreatePersonCommandDto {
    command: "createPerson";
    id: string;
    person: PersonDto;
}

export interface PersonDto {
    readonly id?: string;
    type: string;
    givenName: string;
    familyName: string;
    email?: string;
    phone?: string;
    birthDate?: Date;
}

export interface SubscribeDto {
    request: "Subscribe";
}

export interface UnsubscribeDto {
    request: "Unsubscribe";
}

export interface UpdatePersonCommandDto {
    command: "updatePerson";
    id: string;
    person: PersonDto;
}

export type WebSocketCommandDto =
	{ command: "createPerson" } & CreatePersonCommandDto |
	{ command: "updatePerson" } & UpdatePersonCommandDto;


export type WebSocketMessageDto = WebSocketCommandDto | WebSocketRequestDto;


export type WebSocketRequestDto =
	{ request: "Subscribe" } & SubscribeDto;

