/**
 * Sample API
 * A small example to demonstrate individual problems
 *
 * The version of the OpenAPI document: 0.1.9
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface PetDto {
    pet_type: PetTypeDto;
    name?: string;
    birth_date?: Date;
}

export type PetTypeDto =
    | "cat"
    | "dog"
    | "bird";

export const PetTypeDtoValues: PetTypeDto[] = [
    "cat",
    "dog",
    "bird",
];
