/**
 * Sample API
 * A small example to demonstrate individual problems
 *
 * The version of the OpenAPI document: 0.1.9
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface PetDto {
    pet_type: string;
    name?: string;
    birth_date?: string;
}

export interface PetLocationsDto {
    locations?: { [key: string]: { [key: string]: Array<number>; }; };
}

export interface PetStoreDto {
    pets?: { [key: string]: PetDto; };
}
