/* eslint @typescript-eslint/no-unused-vars: off */
/**
 * User database
 * User database
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    UserDto,
    UserPermissionDto,
} from "../model";

import {
    ApplicationApis,
    DefaultApiInterface,
} from "../api";

function reject(operation: string) {
    return () => Promise.reject(new Error("Unexpected function call " + operation));
}

export function mockApplicationApis({
    defaultApi = mockDefaultApi(),
}: Partial<ApplicationApis> = {}): ApplicationApis {
    return { defaultApi };
}

export function mockDefaultApi(
    operations: Partial<DefaultApiInterface> = {}
): DefaultApiInterface {
    return {
        usersGet: operations.usersGet || reject("DefaultApi.usersGet"),
        usersPost: operations.usersPost || reject("DefaultApi.usersPost"),
    };
}
