/**
 * ReqRes API
 * Fake data CRUD API
 *
 * The version of the OpenAPI document: 1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface LoginPost200ResponseDto {
    token?: string;
}

export interface LoginPost400ResponseDto {
    error?: string;
}

export interface LoginPostRequestDto {
    username?: string;
    email?: string;
    password?: string;
}

export interface RegisterPost200ResponseDto {
    id?: string;
    token?: string;
}

export interface UnknownResourceDto {
    id?: number;
    name?: string;
    year?: number;
    color?: string;
    pantone_value?: string;
}

export interface UserDto {
    id?: number;
    email?: string;
    first_name?: string;
    last_name?: string;
    avatar?: string;
}

export interface UsersGet200ResponseDto {
    page?: number;
    per_page?: number;
    total?: number;
    total_pages?: number;
    data?: Array<UserDto>;
}

export interface UsersIdGet200ResponseDto {
    data?: UserDto;
}

export interface UsersIdPut200ResponseDto {
    updatedAt?: string;
}
