/**
 * Sample API
 * Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
 *
 * The version of the OpenAPI document: 0.1.9
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export type AnyPetDto =
	{ pet_type: "Cat" } & CatDto |
	{ pet_type: "Dog" } & DogDto;


export interface CatAllOfDto {
    hunts?: boolean;
    age?: number;
}

export interface CatDto extends PetDto {
    hunts?: boolean;
    age?: number;
}

export interface DogAllOfDto {
    bark?: boolean;
    breed?: DogAllOfDtoBreedDtoEnum;
}

export type DogAllOfDtoBreedDtoEnum =
    | "Dingo"
    | "Husky"
    | "Retriever"
    | "Shepherd";

export const DogAllOfDtoBreedDtoEnumValues: DogAllOfDtoBreedDtoEnum[] = [
    "Dingo",
    "Husky",
    "Retriever",
    "Shepherd",
];

export interface DogDto extends PetDto {
    bark?: boolean;
    breed?: DogDtoBreedDtoEnum;
}

export type DogDtoBreedDtoEnum =
    | "Dingo"
    | "Husky"
    | "Retriever"
    | "Shepherd";

export const DogDtoBreedDtoEnumValues: DogDtoBreedDtoEnum[] = [
    "Dingo",
    "Husky",
    "Retriever",
    "Shepherd",
];

export interface PetDto {
    pet_type: string;
    name?: string;
    birth_date?: string;
}
