/* eslint @typescript-eslint/no-unused-vars: off */
/**
 * Conversations
 * Conversations for real time and offline peer-to-peer web chat
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    AddMessageToConversationDeltaDto,
    ChangeTrackedDto,
    CommandToServerDto,
    ConversationInfoDto,
    ConversationMessageDto,
    ConversationMessageSnapshotDto,
    ConversationSnapshotDto,
    CreateConversationDeltaDto,
    DeltaDto,
    EventFromServerDto,
    MessageFromServerDto,
    MessageToServerDto,
    RequestToServerDto,
    SnapshotSetDto,
    SubscribeRequestDto,
    UpdateConversationDeltaDto,
} from "../model";

import {
    ApplicationApis,
    DefaultApiInterface,
} from "../api";

function reject(operation: string) {
    return () => Promise.reject(new Error("Unexpected function call " + operation));
}

export function mockApplicationApis({
    defaultApi = mockDefaultApi(),
}: Partial<ApplicationApis> = {}): ApplicationApis {
    return { defaultApi };
}

export function mockDefaultApi(
    operations: Partial<DefaultApiInterface> = {}
): DefaultApiInterface {
    return {
        apiCommandsPost: operations.apiCommandsPost || reject("DefaultApi.apiCommandsPost"),
        apiConversationsGet: operations.apiConversationsGet || reject("DefaultApi.apiConversationsGet"),
    };
}
